# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'BlokSecFramework' do
    
    
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 # Pods for BlokSec
 pod 'KeychainSwift'
 
 # ArcBlock
 pod 'ArcBlockSDK', :git => 'https://github.com/ArcBlock/arcblock-ios-sdk.git'
 pod 'Apollo', :git => 'https://github.com/ArcBlock/apollo-ios.git'
 
end

# ignore all warnings from all pods
inhibit_all_warnings!

target 'BlokSecTests' do
  
  use_frameworks!
  
  end
